/* ----------------------------------------------------------------------------- 
					Append all the state data and label them
					             Ataur Rahaman
							Last update: 10.15.25
							
This do file is to append all the data state data created in "1.read_raw_data.do" 
and save the app data as sadc_2023_state_all.dta

The converted data are in "intermediate_data" folder. The data files are
A. State data
	-sadc_2023_state_a_d.dta
	-sadc_2023_state_e_h.dta
	-sadc_2023_state_i_l.dta
	-sadc_2023_state_m.dta
	-sadc_2023_state_n_p.dta
	-sadc_2023_state_q_t.dta
	-sadc_2023_state_u_z.dta
------------------------------------------------------------------------------*/

* House Keeping
clear all

// set the path
cd "C:\path\to\intermediate_data"

append using sadc_2023_state_a_d sadc_2023_state_e_h sadc_2023_state_i_l sadc_2023_state_m sadc_2023_state_n_p sadc_2023_state_q_t sadc_2023_state_u_z

// check and match data with codebook
tab sitename

// VARIABLE LABELS (from sas input file)
label var sitecode "Site code"
label var sitename "Site name"
label var sitetype "Site type"
label var sitetypenum "1=District, 2=State, 3=National"
label var year "4-digit Year of survey"
label var survyear "1=1991...17=2023"
label var weight "Analysis weight"
label var stratum "Analysis stratum"
label var PSU "Analysis primary sampling unit"
label var record "Record ID"
label var age "1= <=12...7=18+ years old"
label var sex "1=female, 2=male"
label var grade "1=9th...4=12th grade"
label var race4 "4-level race variable"
label var race7 "7-level race variable"
label var stheight "Height in meters"
label var stweight "Weight in kilograms"
label var bmi "Body Mass Index"
label var bmipct "BMI percentile"
label var qnobese "Had obesity"
label var qnowt "Were overweight"
label var q65 "Transgender"
label var q64 "Sexual identity"
label var q63 "Sex of sexual contacts"
label var sexid "Sexual identity"
label var sexid2 "Collapsed sexual identity"
label var sexpart "Sex of sex contact(s)"
label var sexpart2 "Collapsed sex of sex contact(s)"
label var transg "Transgender for YOL"
label var sextrans "Sexual and Gender Identity for YOL"
label var q8 "Seat belt use"
label var q9 "Riding with a drinking driver"
label var q10 "Drinking and driving"
label var q11 "Texting and driving"
label var q12 "Weapon carrying at school"
label var q13 "Gun carrying"
label var q14 "Safety concerns at school"
label var q15 "Threatened at school"
label var q16 "Physical fighting"
label var q17 "Physical fighting at school"
label var q18 "Saw physical violence in neighborhood"
label var q19 "Forced sexual intercourse"
label var q20 "Sexual violence"
label var q21 "Sexual dating violence"
label var q22 "Physical dating violence"
label var q23 "Treated badly because of race or ethnicity"
label var q24 "Bullying at school"
label var q25 "Electronic bullying"
label var q26 "Sad or hopeless"
label var q27 "Considered suicide"
label var q28 "Made a suicide plan"
label var q29 "Attempted suicide"
label var q30 "Injurious suicide attempt"
label var q31 "Ever cigarette use"
label var q32 "Initiation of cigarette smoking"
label var q33 "Current cigarette use"
label var q34 "Smoked > 10 cigarettes"
label var q35 "Electronic vapor product use"
label var q36 "Current electronic vapor use"
label var q37 "EVP from store"
label var q38 "Current smokeless tobacco use"
label var q39 "Current cigar use"
label var q40 "All tobacco product cessation"
label var q41 "Initiation of alcohol use"
label var q42 "Current alcohol use"
label var q43 "Current binge drinking"
label var q44 "Largest number of drinks"
label var q45 "Source of alcohol"
label var q46 "Ever marijuana use"
label var q47 "Initiation of marijuana use"
label var q48 "Current marijuana use"
label var q49 "Ever prescription pain medicine use"
label var q50 "Ever cocaine use"
label var q51 "Ever inhalant use"
label var q52 "Ever heroin use"
label var q53 "Ever methamphetamine use"
label var q54 "Ever ecstasy use"
label var q55 "Illegal injected drug use"
label var q56 "Ever sexual intercourse"
label var q57 "Sex before 13 years"
label var q58 "Number of sex partners"
label var q59 "Current sexual activity"
label var q60 "Alcohol/drugs and sex"
label var q61 "Condom use"
label var q62 "Birth control pill use"
label var q66 "Perception of weight"
label var q67 "Weight loss"
label var q68 "Fruit juice drinking"
label var q69 "Fruit eating"
label var q70 "Green salad eating"
label var q71 "Potato eating"
label var q72 "Carrot eating"
label var q73 "Other vegetable eating"
label var q74 "No soda drinking"
label var q75 "Breakfast eating"
label var q76 "Physical activity >= 5 days"
label var q77 "PE attendance"
label var q78 "Sports team participation"
label var q79 "Concussion"
label var q80 "Social media"
label var q81 "HIV testing"
label var q82 "STD testing"
label var q83 "Oral health care"
label var q84 "Current mental health"
label var q85 "Sleep"
label var q86 "Unstable housing"
label var q87 "Grades in school"
label var qn8 "Did not always wear a seat belt"
label var qn9 "Rode with a driver who had been drinking alcohol"
label var qn10 "Drove a car or other vehicle when they had been drinking alcohol"
label var qn11 "Texted or e-mailed while driving a car or other vehicle"
label var qn12 "Carried a weapon on school property"
label var qn13 "Carried a gun"
label var qn14 "Did not go to school because they felt unsafe at school or on their way to or from school"
label var qn15 "Were threatened or injured with a weapon on school property"
label var qn16 "Were in a physical fight"
label var qn17 "Were in a physical fight on school property"
label var qn18 "Ever saw someone get physically attacked, beaten, stabbed, or shot in their neighborhood"
label var qn19 "Were ever physically forced to have sexual intercourse"
label var qn20 "Experienced sexual violence"
label var qn21 "Experienced sexual dating violence"
label var qn22 "Experienced physical dating violence"
label var qn23 "Felt that they were ever treated badly or unfairly in school because of their race or ethnicity"
label var qn24 "Were bullied on school property"
label var qn25 "Were electronically bullied"
label var qn26 "Felt sad or hopeless"
label var qn27 "Seriously considered attempting suicide"
label var qn28 "Made a plan about how they would attempt suicide"
label var qn29 "Actually attempted suicide"
label var qn30 "Had a suicide attempt that resulted in an injury, poisoning, or overdose that had to be treated by a doctor or nurse"
label var qn31 "Ever smoked a cigarette"
label var qn32 "Smoked a cigarette before age 13 years"
label var qn33 "Currently smoked cigarettes"
label var qn34 "Smoked more than 10 cigarettes per day"
label var qn35 "Ever used an electronic vapor product"
label var qn36 "Currently used an electronic vapor product"
label var qn37 "Usually got their electronic vapor products by buying them themselves in a convenience store, supermarket, discount store, or gas station"
label var qn38 "Currently used smokeless tobacco"
label var qn39 "Currently smoked cigars"
label var qn40 "Tried to quit using all tobacco products"
label var qn41 "Had their first drink of alcohol before age 13 years"
label var qn42 "Currently drank alcohol"
label var qn43 "Currently were binge drinking"
label var qn44 "Reported that the largest number of drinks they had in a row was 10 or more"
label var qn45 "Usually got the alcohol they drank by someone giving it to them"
label var qn46 "Ever used marijuana"
label var qn47 "Tried marijuana for the first time before age 13 years"
label var qn48 "Currently used marijuana"
label var qn49 "Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it"
label var qn50 "Ever used cocaine"
label var qn51 "Ever used inhalants"
label var qn52 "Ever used heroin"
label var qn53 "Ever used methamphetamines"
label var qn54 "Ever used ecstasy"
label var qn55 "Ever injected any illegal drug"
label var qn56 "Ever had sexual intercourse"
label var qn57 "Had sexual intercourse for the first time before age 13 years"
label var qn58 "Had sexual intercourse with four or more persons during their life"
label var qn59 "Were currently sexually active"
label var qn60 "Drank alcohol or used drugs before last sexual intercourse"
label var qn61 "Used a condom during last sexual intercourse"
label var qn62 "Used birth control pills before last sexual intercourse with opposite-sex partner"
label var qn66 "Described themselves as slightly or very overweight"
label var qn67 "Were trying to lose weight"
label var qn68 "Did not drink fruit juice"
label var qn69 "Did not eat fruit"
label var qn70 "Did not eat salad"
label var qn71 "Did not eat potatoes"
label var qn72 "Did not eat carrots"
label var qn73 "Did not eat other vegetables"
label var qn74 "Did not drink a can, bottle, or glass of soda or pop"
label var qn75 "Did not eat breakfast"
label var qn76 "Were physically active at least 60 minutes per day on 5 or more days"
label var qn77 "Attended physical education (PE) classes on 1 or more days"
label var qn78 "Played on at least one sports team"
label var qn79 "Had a concussion from playing a sport or being physically active"
label var qn80 "Used social media several times a day"
label var qn81 "Were ever tested for human immunodeficiency virus (HIV)"
label var qn82 "Were tested for a sexually transmitted disease (STD) other than HIV"
label var qn83 "Saw a dentist"
label var qn84 "Reported that their mental health was most of the time or always not good"
label var qn85 "Got 8 or more hours of sleep"
label var qn86 "Experience unstable housing"
label var qn87 "Described their grades in school as mostly A's or B's"
label var qnfrcig "Currently smoked cigarettes frequently"
label var qndaycig "Currently smoked cigarettes daily"
label var qnfrevp "Currently smoked electronic vapor products frequently"
label var qndayevp "Currently smoked electronic vapor products daily"
label var qnfrskl "Currently used smokeless tobacco frequently"
label var qndayskl "Currently used smokeless tobacco daily"
label var qnfrcgr "Currently smoked cigars frequently"
label var qndaycgr "Currently smoked cigars daily"
label var qntb2 "Currently smoked cigarettes or cigars"
label var qntb3 "Currently smoked cigarettes or cigars or used smokeless tobacco"
label var qntb4 "Currently smoked cigarettes or cigars or used smokeless tobacco or electronic vapor products"
label var qntb5 "Currently smoked cigarettes or used electronic vapor products"
label var qniudimp "Used an IUD (such as Mirena or ParaGard) or implant (such as Implanon or Nexplanon) before last sexual intercourse with an opposite-sex partner"
label var qnothhpl "Used birth control pills; an IUD (such as Mirena or ParaGard) or implant (such as Implanon or Nexplanon); or a shot (such as Depo-Provera), patch (such as OrthoEvra), or birth control ring (such as NuvaRing) before last sexual intercourse with an opposite-"
label var qnbcnone "Did not use any method to prevent pregnancy during last sexual intercourse with an opposite-sex partner"
label var qnfr0 "Did not eat fruit or drink 100% fruit juices"
label var qnfr1 "Ate fruit or drank 100% fruit juices one or more times per day"
label var qnfr2 "Ate fruit or drank 100% fruit juices two or more times per day"
label var qnveg0 "Did not eat vegetables"
label var qnveg1 "Ate vegetables one or more times per day"
label var qnveg2 "Ate vegetables two or more times per day"
label var qnveg3 "Ate vegetables three or more times per day"
label var qnsoda1 "Drank a can, bottle, or glass of soda or pop one or more times per day"
label var qnsoda2 "Drank a can, bottle, or glass of soda or pop two or more times per day"
label var qnbk7day "Ate breakfast on all 7 days"
label var qnpa0day "Did not participate in at least 60 minutes of physical activity on at least 1 day"
label var qnpa7day "Were physically active at least 60 minutes per day on all 7 days"
label var qndlype "Attended physical education (PE) classes on all 5 days"
label var qnnodnt "Never saw a dentist"
label var qbasicneedsace "Household adult tried hard to meet basic needs ACEs"
label var qclose2people "Feel close to people at their school"
label var qconsentsexcont "Verbally asked for consent last sexual contact"
label var qcurrentopioid "Current Rx Pain med w/out Rx"
label var qemoabuseace "Parental emotional abuse ACEs"
label var qhallucdrug "Ever used hallucinogenic drugs"
label var qincarparentace "Ever incarcerated parent/guardian ACEs"
label var qintviolenceace "Adults in home intimate partner violence ACEs"
label var qlivedwabuseace "Ever lived w/parent/guardian w/substance abuse ACEs"
label var qlivedwillace "Ever lived with parent/guardian w mental illness ACEs"
label var qmusclestrength "Muscle strengthening"
label var qparentalmonitoring "Parental monitoring"
label var qphyabuseace "Parental physical abuse ACEs"
label var qphyviolenceace "Past 12-month incidence of physical violence"
label var qsexabuseace "Ever sexual abuse by adult or older person ACEs"
label var qsportsdrink "Sports drinks"
label var qsunburn "Sunburn"
label var qtalkadultace "Lifetime prevalence of feeling able to talk to adults about feelings"
label var qtalkfriendace "Lifetime prevalence of feeling supported by friends"
label var qtransgender "Transgender"
label var qtreatbadlyace "Lifetime prevalence of perceived sexual minority discrimination"
label var qunfairlyace "Lifetime prevalence of perceived racial/ethnic injustice"
label var qunfairlydisc "Unfairly disciplined at school"
label var qverbalabuseace "Past 12-month incidence of emotional violence"
label var qwater "Plain water"
label var qnbasicneedsace "Reported that an adult in their household most of the time or always tried to make sure their basic needs were met"
label var qnclose2people "Strongly agree or agree that they feel close to people at their school"
label var qnconsentsexcont "Verbally asked for consent the last time they had sexual contact"
label var qncurrentopioid "Currently took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it"
label var qnemoabuseace "Reported that a parent or other adult in their home most of the time or always insulted them or put them down"
label var qnhallucdrug "Ever used hallucinogenic drugs"
label var qnillict "Ever used select illicit drugs"
label var qnincarparentace "Have ever been separated from a parent or guardian because they went to jail, prison, or a detention center"
label var qnintviolenceace "Reported that their parents or other adults in their home most of the time or always slapped, hit, kicked, punched, or beat each other up"
label var qnlivedwabuseace "Ever lived with a parent or guardian who was having a problem with alcohol or drug use"
label var qnlivedwillace "Ever lived with a parent or guardian who had severe depression, anxiety, or another mental illness, or was suicidal"
label var qnmusclestrength "Did exercises to strengthen or tone their muscles on three or more days"
label var qnparentalmonitoring "Reported that their parents or other adults in their family most of the time or always know where they are going or with whom they will be"
label var qnphyabuseace "Reported that a parent or other adult in their home most of the time or always hit, beat, kicked, or physically hurt them in any way"
label var qnphyviolenceace "Reported that a parent or other adult in their home hit, beat, kicked, or physically hurt them in any way one or more times"
label var qnsexabuseace "Reported that an adult or person at least 5 years older than them ever made them do sexual things they did not want to do"
label var qnsportsdrink "Did not drink a can, bottle, or glass of a sports drink"
label var qnspdrk1 "Drank a can, bottle, or glass of a sports drink one or more times per day"
label var qnspdrk2 "Drank a can, bottle, or glass of a sports drink two or more times per day"
label var qnsunburn "Had a sunburn"
label var qntalkadultace "Most of the time or always feel that they are able to talk to an adult in their family or another caring adult about their feelings"
label var qntalkfriendace "Most of the time or always feel that they are able to talk to a friend about their feelings"
label var qntransgender "Are transgender"
label var qntreatbadlyace "Felt that they were ever treated badly or unfairly because they are or people think they are lesbian, gay, bisexual, transgender, or questioning"
label var qnunfairlyace "Felt that they were treated badly or unfairly because of their race or ethnicity"
label var qnunfairlydisc "Have been unfairly disciplined at school"
label var qnverbalabuseace "Reported that a parent or other adult in their home hit, beat, kicked, or physically hurt them in any way one or more times"
label var qnwater "Did not drink a bottle or glass of plain water"
label var qnwater1 "Drank a bottle or glass of plain water one or more times per day"
label var qnwater2 "Drank a bottle or glass of plain water two or more times per day"
label var qnwater3 "Drank a bottle or glass of plain water three or more times per day"


// save the appended data
save sadc_2023_state_all